In [20]:
# The %... is an iPython thing, and is not part of the Python language.
# In this case we're just telling the plotting library to draw things on
# the notebook, instead of on a separate window.
%matplotlib inline 
#this line above prepares IPython notebook for working with matplotlib

# See all the "as ..." contructs? They're just aliasing the package names.
# That way we can call methods like plt.plot() instead of matplotlib.pyplot.plot().

import numpy as np # imports a fast numerical programming library
import scipy as sp #imports stats functions, amongst other things
import matplotlib as mpl # this actually imports matplotlib
import matplotlib.cm as cm #allows us easy access to colormaps
import matplotlib.pyplot as plt #sets up plotting under plt
import pandas as pd #lets us handle data as dataframes
#sets up pandas table display
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns #sets up styles and gives us more plotting options

In [21]:
%cd Documents\DS Courses\kaggle-berlin\titanic

[Error 3] The system cannot find the path specified: u'Documents/DS Courses/kaggle-berlin/titanic'
C:\Users\ivana\Documents\DS courses\kaggle-berlin\titanic


In [22]:
Xtrain=pd.read_csv('train.csv')
Xtest=pd.read_csv('test.csv')

Xtrain.drop(['Cabin', 'Ticket','Name'], axis=1, inplace=True)
Xtest.drop(['Cabin', 'Ticket','Name'], axis=1, inplace=True)

#Fill NaNs with medium age
Xtrain.Age.fillna(Xtrain.Age.median(), inplace=True)
Xtest.Age.fillna(Xtrain.Age.median(), inplace=True)

#Xtrain.Embarked.loc[Xtrain.Embarked=='S']=0
#Xtrain.Embarked.loc[Xtrain.Embarked=='C']=1
#Xtrain.Embarked.loc[Xtrain.Embarked=='Q']=2
#Xtest.Embarked.loc[Xtest.Embarked=='S']=0
#Xtest.Embarked.loc[Xtest.Embarked=='C']=1
#Xtest.Embarked.loc[Xtest.Embarked=='Q']=2

#Make Sex binary data and fill NaNs with most frequent value
Xtrain.Sex.loc[Xtrain.Sex=='male']=0
Xtrain.Sex.loc[Xtrain.Sex=='female']=1
Xtrain.Sex.fillna(np.argmax(Xtrain.groupby('Sex').Sex.count()), inplace=True)
Xtest.Sex.loc[Xtest.Sex=='male']=0
Xtest.Sex.loc[Xtest.Sex=='female']=1
Xtest.Sex.fillna(np.argmax(Xtrain.groupby('Sex').Sex.count()), inplace=True)

#Fill test fare NaNs with median fare value
Xtest.Fare.fillna(Xtrain.Fare.median(), inplace=True)

#Fill Embarked NaNs with most frequent occuring error
Xtrain.Embarked.fillna(np.argmax(Xtrain.groupby('Embarked').Embarked.count()), inplace=True)
Xtest.Embarked.fillna(np.argmax(Xtrain.groupby('Embarked').Embarked.count()), inplace=True)
#np.argmax(Xtest.groupby('Embarked').Embarked.count())

In [23]:
#dummies= pd.get_dummies(Xtrain.Parch)
#Xtrain[Xtrain.Parch.unique()] = dummies
#Xtrain.drop('Parch',axis=1, inplace=True)

#dummies = pd.get_dummies(Xtest.Parch)
#Xtest[Xtest.Parch.unique()] = dummies
#Xtest.drop('Parch',axis=1, inplace=True)

dummies = pd.get_dummies(Xtrain.Embarked)
Xtrain[Xtrain.Embarked.unique()] = dummies
dummies = pd.get_dummies(Xtest.Embarked)
Xtest[Xtest.Embarked.unique()] = dummies
col_to_add = np.setdiff1d(Xtrain.columns, Xtest.columns)

# add these columns to test, setting them equal to zero
for c in col_to_add:
    Xtest[c] = 0

# select and reorder the test columns using the train columns
Xtest = Xtest[Xtrain.columns]
Xtrain.drop('Embarked',axis=1, inplace=True)
           

Xtest.drop('Embarked',axis=1, inplace=True)

#dummies = pd.get_dummies(X_train.Pclass)
#X_test[X_test.Pclass.unique()] = dummies
#X_test.drop('Pclass',axis=1, inplace=True)

#X_train.drop(['Cabin', 'Ticket','Name'], axis=1, inplace=True)
#X_test.drop(['Cabin', 'Ticket','Name'], axis=1, inplace=True)
#X_train.head()

In [24]:
Xtrain.columns

Index([u'PassengerId', u'Survived', u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Fare', u'S', u'C', u'Q'], dtype='object')

In [25]:

X_train = Xtrain.drop(['PassengerId','Survived'], axis=1)
X_test = Xtest.drop(['PassengerId','Survived'], axis=1)


In [26]:
X_test.columns.values

array(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'S', 'C', 'Q'], dtype=object)

In [27]:
Y_train = Xtrain['Survived']

In [28]:
type(Y_train)

pandas.core.series.Series

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier

from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import train_test_split

In [30]:
xtrain, xtest, ytrain, ytest = train_test_split(X_train,Y_train)
model1=LogisticRegression(penalty='l1')
model2=LogisticRegression(penalty='l2')
model3=RidgeClassifier()
alphas = np.array([1,0.1,0.01,0.001,0.0001,0])
# create and fit a ridge regression model, testing each alpha

grid = GridSearchCV(estimator=model3, param_grid=dict(alpha=alphas))
param_grid = {'C': [0.001, 0.01, 0.1,1, 10, 100, 1000] }
cv1 = grid.fit(xtrain, ytrain)

In [31]:
cv1 = GridSearchCV(estimator=model1, param_grid=param_grid)
cv1 = cv1.fit(xtrain, ytrain)

In [32]:
score1 = grid.best_score_
print(score1)
print(grid.best_params_)
grid.predict(xtest)
grid.score(xtest,ytest)

0.808383233533
{'alpha': 1.0}


0.7488789237668162

In [33]:
cv2 = GridSearchCV(estimator=model2, param_grid=param_grid)
cv2 = cv2.fit(X_train, Y_train)

score2 = cv2.best_score_
print(score2)
cv2.best_params_

0.789001122334


{'C': 1}

In [34]:
model = LogisticRegression(C=0.1, penalty='l1')

In [35]:
model = model.fit(X_train, Y_train)
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
Pclass    418 non-null int64
Sex       418 non-null int64
Age       418 non-null float64
SibSp     418 non-null int64
Parch     418 non-null int64
Fare      418 non-null float64
S         418 non-null float64
C         418 non-null float64
Q         418 non-null float64
dtypes: float64(5), int64(4)
memory usage: 29.5 KB


In [36]:
model.predict(X_test)

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0,

In [37]:
model.score(xtest,ytest)

0.77130044843049328

In [38]:
from sklearn.ensemble import RandomForestClassifier


In [39]:
rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True) 

param_grid = { 
    'n_estimators': [1, 700],
    'max_features': ['auto', 'sqrt', 'log2']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(xtrain, ytrain)

C:\Anaconda2\lib\site-packages\sklearn\ensemble\forest.py:439: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "


GridSearchCV(cv=5, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=50, n_jobs=-1, oob_score=True, random_state=None,
            verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [1, 700], 'max_features': ['auto', 'sqrt', 'log2']},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

In [40]:
CV_rfc.best_params_
print(CV_rfc.score(xtest,ytest))
CV_rfc.predict(xtest)
#CV_rfc.best_score_

0.775784753363


array([0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [41]:
random_forest = RandomForestClassifier(n_estimators=700, max_features='log2')
#rfc2 = RandomForestClassifier(max_features= 'sqrt' ,n_estimators=200) 

In [42]:
random_forest.fit(xtrain,ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='log2', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=700, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [43]:
#random_forest.predict(X_train)
random_forest.score(xtest,ytest)

0.7847533632286996

In [44]:
print(X_train.columns)
print(X_test.columns)
CV_rfc.score(xtest,ytest)

Index([u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Fare', u'S', u'C', u'Q'], dtype='object')
Index([u'Pclass', u'Sex', u'Age', u'SibSp', u'Parch', u'Fare', u'S', u'C', u'Q'], dtype='object')


0.77578475336322872

In [49]:
Y_pred= CV_rfc.predict(X_test)
print(Y_pred.shape)
print(ytest.shape)

X_test
CV_rfc.score(xtest,ytest)

(418L,)
(223L,)


0.77578475336322872

In [46]:
Y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0,

In [51]:
submission = pd.DataFrame({
        "PassengerId": Xtest["PassengerId"],
        "Survived": Y_pred
    })
submission.to_csv('titanic.csv', index=False)

In [42]:
test_data["PassengerId"]

0       892
1       893
2       894
3       895
4       896
5       897
6       898
7       899
8       900
9       901
10      902
11      903
12      904
13      905
14      906
15      907
16      908
17      909
18      910
19      911
20      912
21      913
22      914
23      915
24      916
25      917
26      918
27      919
28      920
29      921
       ... 
388    1280
389    1281
390    1282
391    1283
392    1284
393    1285
394    1286
395    1287
396    1288
397    1289
398    1290
399    1291
400    1292
401    1293
402    1294
403    1295
404    1296
405    1297
406    1298
407    1299
408    1300
409    1301
410    1302
411    1303
412    1304
413    1305
414    1306
415    1307
416    1308
417    1309
Name: PassengerId, dtype: int64